src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use libphonenumber\PhoneNumber;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use ZipCodeValidator\Constraints\ZipCode;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber as AssertPhoneNumber;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Il existe un compte avec cet email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\Email(
        message: 'L\'adresse e-mail {{ value }} est incorrecte',
    )]
    private ?string $email = null;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $authCode;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 3,
        max: 30,
        minMessage: 'Votre prénom doit comporter au moins {{ limit }} caractères',
        maxMessage: 'Votre prénom ne peut excéder {{ limit }} caractères',
    )]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 2,
        minMessage: 'Votre nom doit comporter au moins {{ limit }} caractères',
    )]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(
        message: 'Merci d\'indiquer votre adresse'
    )]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    #[ZipCode([
        'iso' => 'FR',
        'message' => 'Le code postal n\'est pas valide'
    ])]
    private ?string $postalCode = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(
        message: 'Merci d\'indiquer votre ville'
    )]
    private ?string $city = null;

    #[ORM\Column(type: 'phone_number')]
    #[AssertPhoneNumber(defaultRegion: 'FR')]
    private ?PhoneNumber $phone = null;

    #[ORM\Column]
    private bool $isVerified = true;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $resetToken = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdTokenAt = null;

    /**
     * @var Collection<int, Lesson>
     */
    #[ORM\OneToMany(targetEntity: Lesson::class, mappedBy: 'user')]
    private Collection $lessons;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Avatar $avatar = null;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Invitation $invitation = null;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'user')]
    private Collection $comments;

    /**
     * @var Collection<int, Like>
     */
    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'user')]
    private Collection $likes;

    /**
     * @var Collection<int, Purchase>
     */
    #[ORM\OneToMany(targetEntity: Purchase::class, mappedBy: 'user')]
    private Collection $purchases;

    /**
     * @var Collection<int, Testimonial>
     */
    #[ORM\OneToMany(targetEntity: Testimonial::class, mappedBy: 'author', orphanRemoval: true)]
    private Collection $testimonials;

    /**
     * @var Collection<int, UserDevice>
     */
    #[ORM\OneToMany(targetEntity: UserDevice::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $userDevices;

    /**
     * @var Collection<int, QuizResult>
     */
    #[ORM\OneToMany(targetEntity: QuizResult::class, mappedBy: 'user')]
    private Collection $quizResults;

    /**
     * @var Collection<int, Certificate>
     */
    #[ORM\OneToMany(targetEntity: Certificate::class, mappedBy: 'user')]
    private Collection $certificates;

    public function __construct()
    {
        $this->lessons = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->purchases = new ArrayCollection();
        $this->testimonials = new ArrayCollection();
        $this->userDevices = new ArrayCollection();
        $this->quizResults = new ArrayCollection();
        $this->certificates = new ArrayCollection();
    }

    public function __toString()
    {
        return "{$this->firstname} {$this->lastname}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): static
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?PhoneNumber
    {
        return $this->phone;
    }

    public function setPhone(?PhoneNumber $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): static
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getCreatedTokenAt(): ?\DateTimeImmutable
    {
        return $this->createdTokenAt;
    }

    public function setCreatedTokenAt(?\DateTimeImmutable $createdTokenAt): static
    {
        $this->createdTokenAt = $createdTokenAt;

        return $this;
    }

    /**
     * Retourne le nom complet de l'utilisateur
     *
     * @return string
     */
    public function getFullname(): string
    {
        return "{$this->firstname} {$this->lastname}";
    }

    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new \LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }

    /**
     * @return Collection<int, Lesson>
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): static
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons->add($lesson);
            $lesson->setUser($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): static
    {
        if ($this->lessons->removeElement($lesson)) {
            // set the owning side to null (unless already changed)
            if ($lesson->getUser() === $this) {
                $lesson->setUser(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?Avatar
    {
        return $this->avatar;
    }

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use DateTimeImmutable;
use App\Service\SendMailService;
use App\Repository\UserRepository;
use App\Form\ResetPasswordFormType;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\ResetPasswordRequestFormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;

class SecurityController extends AbstractController
{
    public function __construct(protected RequestStack $requestStack)
    {}

    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils, Request $request): Response
    {
        $session = $this->requestStack->getSession();

        $targetPath = $request->query->get('target', $session->get('_security.main.target_path'));
        if ($targetPath) {
            $session->set('_security.main.target_path', $targetPath);
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route('/forgot-password', name: 'app_forgot_pw')]
    public function forgotPw(Request $request, UserRepository $userRepository, TokenGeneratorInterface $tokenGeneratorInterface, EntityManagerInterface $em, SendMailService $mail): Response
    {
        $form = $this->createForm(ResetPasswordRequestFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $userRepository->findOneBy([
                'email' => $form->get('email')->getData()
            ]);

            if ($user) {
                // On génère un token de réinitialisation
                $token = $tokenGeneratorInterface->generateToken();
                $now = new DateTimeImmutable();
                $user->setResetToken($token);
                $user->setCreatedTokenAt($now);
                $em->flush();

                // On génère un lien de réinitialisation du mot de passe
                $url = $this->generateUrl('app_reset_pw', ['token' => $token], UrlGeneratorInterface::ABSOLUTE_URL);
                // On crée les données du mail
                $context = [
                    'url' => $url,
                    'user' => $user
                ];
                // Envoi du mail
                $mail->sendMail(
                    null,
                    'Infos de l\'application sym-numbers',
                    $user->getEmail(),
                    'Réinitialisation de mot de passe',
                    'password_reset',
                    $context
                );

                $this->addFlash('success', 'Email envoyé avec succès');
                return $this->redirectToRoute('app_login');
            }
            // $user est null
            $this->addFlash('danger', 'Un problème est survenu');
            return $this->redirectToRoute('app_login');
        }

        return $this->render('security/reset_password_request.html.twig', [
            'formView' => $form,
        ]);
    }

    #[Route('/forgot-password/{token}', name: 'app_reset_pw')]
    public function resetPw($token, Request $request, UserRepository $userRepository, EntityManagerInterface $em, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        // On vérifie si on a ce token dans la base
        $user = $userRepository->findOneBy([
            'resetToken' => $token
        ]);

        // On vérifie si le createdTokenAt = now - 3h
        $now = new DateTimeImmutable();
        if ($now > $user->getCreatedTokenAt()->modify('+ 3 hour')) {
            $this->addFlash('warning', 'Votre demande de mot de passe a expiré. Merci de la renouveller.');
            return $this->redirectToRoute('app_forgot_pw');
        }

        // On vérifie si l'utilisateur existe
        $form = $this->createForm(ResetPasswordFormType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // On efface le token et sa date de création
            $user->setResetToken(null);
            $user->setCreatedTokenAt(null);

            // On enregistre le nouveau mot de passe en le hashant
            $user->setPassword(
                $userPasswordHasher->hashPassword($user, $form->get('plainPassword')->getData())
            );
            $em->flush();

            $this->addFlash('success', 'Mot de passe changé avec succès');
            return $this->redirectToRoute('app_login');
        }

        return $this->render('security/reset_password.html.twig', [
            'passForm' => $form
        ]);

        // Si le token est invalide on redirige vers le login
        $this->addFlash('danger', 'Jeton invalide');
        return $this->redirectToRoute('app_login');
    }

    #[Route(path: '/login/success', name: 'app_login_success')]
    public function loginSuccess(): Response
    {
        $session = $this->requestStack->getSession();

        // Récupérer l'URL de redirection stockée
        $targetPath = $session->get('_security.main.target_path', $this->generateUrl('home_index'));

        // Supprimer la valeur de la session pour éviter une redirection non voulue plus tard
        $session->remove('_security.main.target_path');

        return $this->redirect($targetPath);
    }
}

templates/security/2fa_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vérifier le compte
{% endblock %}

{% block body %}
	<div class="container pt-5">
		<div class="card card-fill">
			<div class="card-body">
				<div class="my-8 mx-auto" style="width: 480px;">
					<h1 class="text-center mb-4 fs-4">Vérifier le compte</h1>
					<p class="mb-3 text-center text-muted">
						Nous avons envoyé un code de vérification à
						<span class="fw-bold">{{ app.user.email }}</span>
					</p>
					{# Authentication errors #}
					{% if authenticationError %}
						<div class="alert alert-danger">{{ authenticationError|trans(authenticationErrorData, 'SchebTwoFactorBundle') }}</div>
					{% endif %}

					<form class="form" action="{{ checkPathUrl ? checkPathUrl: path(checkPathRoute) }}" method="post">
						<div class="form-group mb-3">
							<label for="_auth_code" class="label-for-2fa">Code  de vérification</label>
							<p class="widget mb-0">
								<input id="_auth_code" class="form-control-2fa" placeholder="ex. 170170" type="text" name="{{ authCodeParameterName }}" autocomplete="one-time-code" autofocus {# https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete If your 2fa methods are using numeric codes only, add these attributes for better user experience: inputmode="numeric" pattern="[0-9]*" #}/>
							</p>
							<small class="form-2fa-text text-muted">Votre code de vérification est valable pendant 30 minutes.</small>
						</div>

						{% if displayTrustedOption %}
							<div class="custom-control-2fa custom-checkbox-2fa mb-3">
								<p class="widget mb-0">
									<input id="_trusted" class="custom-control-input-2fa" type="checkbox" name="{{ trustedParameterName }}"/>
									<label for="_trusted" class="custom-control-label-2fa">Faites confiance à ce dispositif pour éviter toute vérification supplémentaire</label>
								</p>
							</div>
						{% endif %}
						{% if isCsrfProtectionEnabled %}
							<input type="hidden" name="{{ csrfParameterName }}" value="{{ csrf_token(csrfTokenId) }}">
						{% endif %}
						<p class="submit"><input type="submit" class="btn btn-md btn-dark" value="{{ "login"|trans({}, 'SchebTwoFactorBundle') }}"/></p>
					</form>
					<div class="text-center mt-4">
						<span class="text-muted">Vous ne voulez pas effectuer une authentification à 2 facteurs ?
							<u>
								<p class="cancel mb-0">
									<a href="{{ logoutPath }}">{{ "cancel"|trans({}, 'SchebTwoFactorBundle') }}</a>
								</p>
							</u>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Se connecter
{% endblock %}

{% block body %}
	<div class="container pt-5">
		<div class="card card-fill">
			<div class="card-body">
				<div class="my-8 mx-auto" style="width: 480px;">
					<h1 class="text-center mb-4 fs-4">Se connecter à l'application
						{{ appName }}</h1>
					<form method="post">
						{% if error %}
							<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
						{% endif %}

						{% if app.user %}
							<div class="mb-3">
								You are logged in as
								{{ app.user.userIdentifier }},
								<a href="{{ path('app_logout') }}">Logout</a>
							</div>
						{% endif %}

						<div class="form-group mb-3">
							<label for="username" class="form-label lh-label fw-semibold">Votre email :</label>
							<input type="email" value="{{ last_username }}" name="_username" id="username" class="form-control form-control-login" autocomplete="email" required autofocus placeholder="e.g. picard@starfleet.org">
						</div>
						<div class="form-group mb-3">
							<label for="password" class="form-label lh-label fw-semibold">Votre mot de passe :</label>
							<div class="position-relative">
								<input type="password" name="_password" id="password" class="form-control form-control-login" autocomplete="current-password" required placeholder="••••••••" {{ stimulus_controller('symfony/ux-toggle-password/toggle-password', { visibleLabel: 'Afficher', hiddenLabel: 'Masquer', buttonClasses: ['toggle-password-button'], } ) }}>
							</div>
						</div>

						<input type="hidden" name="_csrf_token" data-controller="csrf-protection" value="{{ csrf_token('authenticate') }}">

						<button class="btn btn-md btn-dark" type="submit">
							<span>Se connecter</span>
						</button>
                        <div class="row mt-3">
							<div class="checkbox col-md-6 text-start">
								<label>
									<input type="checkbox" name="_remember_me">
									Se souvenir de moi
								</label>
							</div>
						</div>
					</form>
                    <div class="d-flex flex-column text-center mt-4">
						<span class="text-muted">Pas encore inscrit(e) ?
							<a href="{{ path('app_register') }}">M'inscrire</a>
						</span>
						<span class="text-muted">
							Vous avez oublié votre mot de passe&nbsp;?
							<u>
								<a href="{{ path('app_forgot_pw') }}" class="text-decoration-none">Le réinitialiser</a>
							</u>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/security/reset_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réinitialisation du mot de passe
{% endblock %}

{% block body %}
	<div class="container pt-5">
		<div class="card card-fill">
			<div class="card-body">
				<div class="my-8 mx-auto" style="width: 480px;">
					<h1 class="text-center mb-4 fs-4">Réinitialisation du mot de passe</h1>
					{{ form_errors(passForm) }}
					{{ form_start(passForm) }}
					<div class="row">
						<div class="col-12">
							{{ form_row(passForm.plainPassword, {'attr': {'class': 'my-custom-class'}}) }}
							{% include "partials/_entropy.html.twig" %}
						</div>
					</div>
					<button id="submit-reset-pw" type="submit" class="btn btn-md btn-dark" disabled>
						<span>Réinitialiser le mot de passe</span>
					</button>
					{{ form_end(passForm) }}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block importmap %}
	{# do NOT call parent() #}

	{{ importmap(['app', 'resetpw']) }} #}
{% endblock %}

templates/security/reset_password_request.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réinitialisation de mot de passe
{% endblock %}

{% block body %}
	<div class="container pt-5">
		<div class="card card-fill">
			<div class="card-body">
				<div class="my-8 mx-auto" style="width: 480px;">
					<h1 class="text-center mb-4 fs-4 fw-bold">Réinitialiser le mot de passe</h1>
					<p class="text-lg mb-4 text-center text-muted">Pour réinitialiser votre mot de passe, veuillez saisir votre email ci-dessous. Un email vous sera envoyé avec la procédure de réinitialisation.</p>
					{{ form_start(formView) }}
					{{ form_errors(formView) }}
					<div class="row mb-3">
						{{ form_row(formView.email) }}
					</div>
					<button type="submit" class="btn btn-md btn-dark">
						<span>Envoyer un e-mail de réinitialisation</span>
					</button>
					{{ form_end(formView) }}
					<div class="text-center mt-4">
						<span class="text-muted">
							Vous souvenez-vous de votre mot de passe&nbsp;?
							<u>
								<a href="{{ path('app_login') }}" class="text-decoration-none">Se connecter</a>
							</u>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}